### ISSUE TITLE
String length

### ISSUE THREAD

**Issue by gregjwinter** [songzh96/node-red-contrib-crestron#11]
Is it possible to change (I assume this would be in the SIMPL+ code) the string length array to handle 180 characters?  In my instance, Node-Red is sending out a sting of 175 characters and I only get 131 characters back in Crestron SIMPL windows program.  Otherwise the code works perfectly for my application - thank you for writing this.  Will be sure to send you some $ for use in my home automation system.

**Comment by gregjwinter** [comment]
Can you send me email address linked to PayPal so I can send you a donation?  My email is greg@gregjwinter.com  Thank you.

**Comment by insecttt** [comment]
Hi,
I apologize for the late response.
I work a lot and unfortunately I don't have time to play with Crestron. I
work in a company that professionally programs Crestron. I will ask my
colleagues if this parameter can be changed.

I am a designer and programming is just fun at home for me.

I haven't dealt with Node-Red and Crestron since my last contact with you.
I hope I will find a moment now and come back to play in my apartment.

Initially, crestron in series 3 should be able to receive 255 characters,
but sometimes it has a problem with that. Series 4 is coming, maybe it will
improve here.

For starters, try to use a *Serial Gather* block in it, you can define a
string of 254 characters. Sometimes it helps.

I will ask my colleagues if it is possible to change the parameter you
wrote about.

I greet
Marcin

wt., 6 paź 2020 o 15:25 gregjwinter <notifications@github.com> napisał(a):

**Comment by insecttt** [comment]
Thank you, but you don't have to.
You when you did something for me, so I'll try to do something for you.

I will ask my professional programmers, maybe they know the solution to
your problem.

greetings
Marcin

wt., 6 paź 2020 o 15:34 gregjwinter <notifications@github.com> napisał(a):

**Comment by insecttt** [comment]
Do I understand well?
You send 175 characters in Node-Red, in Simpl Crestron you only receive 131?

as a quick idea:

https://www.crestron.com/getmedia/d5804ad4-a148-46de-a7dd-109755b04256/mg_simpl_plus_language_ref_1

check:

1) BUFFER_INPUT

[image: image.png]


2)  Check if the $ signal (string from node red) is not connected to the
Pernament String module with the defined number of declines.

3) My colleagues suggest using the Serial Gather block,
be it in Simpl or in Simpl +, try to define the length of e.g. 180
characters, and give the sign of the end of your string.

This Gather solves similar problems.

[image: image.png]

4) In Simpl + you define the signals for string
for example:
STRING NodeRed [100]; // the value must be above 175 for you
Check the value in square brackets, here you define max. string length. But
you certainly know this :).

//

Sometimes I make simple mistakes so it's worth checking this out. I am not
good at Simpl + but if you fail to fix this problem, I will ask our
developers for help :)

What about you? How are you feeling ? all OK?
Here in Poland, the second wave of Covid begins,
problems begin in hospitals, I work from home again.

Write if I helped at least a little, there is still Crestron True Blue
Support, so if you fail, write to me.

Do you have access to Crestron resources ?? Have an account on crestron?

Greetings,


wt., 6 paź 2020 o 15:25 gregjwinter <notifications@github.com> napisał(a):

**Comment by songzh96** [comment]
Hi @insecttt 
Thanks for your help.

I will fix the problem in next version.

Hope everything is fine with you
Pay attention to protecting COVID

Best Regards
Songzh

**Comment by insecttt** [comment]
Most colleagues say that this is a typical problem at Crestron, which is
poorly coping with long series.

You have to define a unique character in your program (Node-Red) at the end
of the string (this 175 characters), which cannot appear in the middle of a
long string. Then use the Gather Serial block and define this unique
character from your string in it.

The gather will keep collecting incoming signs to buffer until it gets a
unique sign. When your unique character reaches it, it will send the entire
collected frame.

A friend says that the crestron divides long thongs into smaller ones,
therefore the ToolBox Debugger sometimes displays split strings or obciente.

This should fix the problem, you have to try and test the solution.

Start testing from there.
Good luck

Marcin

pt., 16 paź 2020 o 11:02 songzh96 <notifications@github.com> napisał(a):
