### ISSUE TITLE
Error in sending to nodered char ":"

### ISSUE THREAD

**Issue by mgmatteo** [songzh96/node-red-contrib-crestron#13]
Hi, I think I found another strange behaviour.
If I send char ":" to nodered from the crestron processor, the string gets truncated.
for example
`{"name":"light_I","value":"{"state":"ON","transition":"0"}"}`
will result in receiving `{"name"`
Another example:
If I send `one:two` i receive just `one`, but if I send `one@two` I receive the full string.
Tried with different characters but so far only ":" is bracking the output

**Comment by songzh96** [comment]
Hi mgmatteo
I’m very busy at work recently, I will deal with this problem when I’m free



Best Regards&nbsp;
Songzh&nbsp;

------------------ Original ------------------

**Comment by songzh96** [comment]
Hi @mgmatteo 
Because I use: as the delimiter, everything after the symbol will be intercepted
