### ISSUE TITLE
Not passing all strings.

### ISSUE THREAD

**Issue by Krkconsult** [songzh96/node-red-contrib-crestron#14]
Crestron Program needs to be restarted because not all string values update or passed to Crestron.
Noted Red shows connected and debug shows data correctly to CrestNode. However, CrestNode strings show "<empty>" in Crestron ToolBox debug console.

SIMPL Windows:  4.15 (build: 4.1500.11)
SIMPL+  4.06 (build: 4.0600.00)

INCLUDE4_2SERIES.DAT Version Information:
        (2 Series)  : 1.80
INCLUDE4.DAT Version Information:
        (3 & 4 Series)  : 2.14.157
Symlib2.Tio 1139  04/15/2021 07:20:24PM 
  iodev.tio 1139  04/15/2021 07:20:24PM 

Other Crestron SW:
        Device Database: 200.75 (build: 200.7500.001.00)
        Crestron Database (cnctrldb22000.mdb) :  205.05 (build: 205.0500.004.00)
        Crestron Toolbox: 3.09p20 (build: 3.0920.0042.0)
        SIMPL+ Cross Compiler: 1.3

**Comment by songzh96** [comment]
try use 4 serials demo again

**Comment by Krkconsult** [comment]
It was running fairly reliably until I was forced to update my cp3n recently when flash was no longer supported. 

Both my implementation and your demo will run for awhile sometimes up to about a week the it will loose the serial strings. It still seems to pass analog and digital signals but not the serial. 

There was a March firmware from Crestron that I installed today. I’ll let you know if it holds up.  

Kris K.
