### ISSUE TITLE
Error: CList: could not obtain list mutex (status=-50),(TaskHoldingMutex=SMn001B)

### ISSUE THREAD

**Issue by hhebnes** [songzh96/node-red-contrib-crestron#17]
Hi,

thanks for this contribution. 

I've started to use this contribution with my Crestron MP2E and Node-Red. When I add multiple Cresnodes in SIMPL Windows, I start to get errors when I deploy. This is what I get:

Program Initialized.

MP2E>The SocketGetStatus returns:       1
The MyServer.SocketStatus returns: 1
Server started to 0.0.0.0 on port 9973 (status: 0)
Error: CList: could not obtain list mutex (status=-50),(TaskHoldingMutex=SMn001B)

Error: Unable to get m_pListenList Protection
The SocketGetStatus returns:       1
The MyServer.SocketStatus returns: 1
Server started to 0.0.0.0 on port 9976 (status: 0)
Error: CList: could not obtain list mutex (status=-50),(TaskHoldingMutex=SMn001B)

Error: Unable to get m_pListenList Protection
The SocketGetStatus returns:       1
The MyServer.SocketStatus returns: 1
Server started to 0.0.0.0 on port 9975 (status: 0)
The SocketGetStatus returns:       1
The MyServer.SocketStatus returns: 1
Server started to 0.0.0.0 on port 9974 (status: 0)

MP2E>ISTAT SPLUS SMn001B
Task is associated with Main Task for Symbol S-7.22.

![image](https://user-images.githubusercontent.com/448837/201075130-bb51b9e1-363c-4756-9aa3-cf2b040b8e9a.png)

Any chance you would share the password for Crestron to be able to look at it?

**Comment by songzh96** [comment]
Your node-red crestron config host should be the IP of MP2E
