### ISSUE TITLE
Can not find Module in Simpl Windows

### ISSUE THREAD

**Issue by Johannes1116** [songzh96/node-red-contrib-crestron#2]
Hello,
I copy the two SIMPL+ files in my Module Folder but i can´t see it in Simpl Windows.

**Comment by songzh96** [comment]
Hi @Johannes1116 

copy the file(.usp&.ush) to C:\Program Files (x86)\Crestron\Simpl\Usrsplus, and then open SIMPL software options->Reload Device and....

try again

**Comment by Johannes1116** [comment]
I downloaded it a second time copyed it to the folder and refresh the libery but can not find the module. With your KNX-Module the same issue. Have you compiled the Module bevor upload? Or could you create a small demo example to import arived programm?

**Comment by songzh96** [comment]
Demo program uploaded

**Comment by kjevat** [comment]
I think this issue is still there in 1.0.3 release. When using a older versjon it does show up but then i am not able to use Serial and have the 10 analog limit.
