### ISSUE TITLE
Crestron Simple+ "Cresnode.usp" file is password protected and encrypted

### ISSUE THREAD

**Issue by marcodmb** [songzh96/node-red-contrib-crestron#3]
Great job for the module node-red-contrib-crestron, BUT it would be better to check the simple+ code for security reasons.
Thank you!

**Comment by songzh96** [comment]
I ’m having a hard time recently, so I encrypted this file, hh

**Comment by wevkovpower4** [comment]
Could you the file be unlocked, please?
