### ISSUE TITLE
Expand the module to more than 10 outputs?

### ISSUE THREAD

**Issue by EHelgeland** [songzh96/node-red-contrib-crestron#7]
Hi
I have used the module and it works very well. Great job so far!
But is it possible to expand the module so we can get 100-200 outputs instead of 10?
I have already used my 10 outputs and are planning for 30 more :-)

**Comment by songzh96** [comment]
Hi

This is a free trial version, because I think it took me a long time to develop, and I should get the due payment. If you donate to this project, I will open more pins for you

Best Regards
Songzh
