### ISSUE TITLE
Please update the zip file

### ISSUE THREAD

**Issue by kjevat** [songzh96/node-red-contrib-crestron#8]
Hi.
The downloadeble zip file does have a wrong cres node file. When extracting this to the simplwindows program it does not show in the project window. But once I replace it with the oldest file compiled in 24/12 it does compile. Can you update zip with the latest 1.0.3 version of the cres node?

Great work by the way!

**Comment by songzh96** [comment]
Hi

Ok, I will update

you can use Crestron_Modules, that's right. 

Best Regards
Songzh

**Comment by songzh96** [comment]
has already been updated
