### ISSUE TITLE
Should False be working?

### ISSUE THREAD

**Issue by jscales4000** [songzh96/node-red-contrib-crestron#9]
Hi,

Great job by the way. I am trying to send either a bollean false or true dependent on when a sensor is open or closed. True works but false does not. I also tried sending a 1 or 0 via string inject. Any thoughts on if I am doing something wrong?

**Comment by songzh96** [comment]
You need give the signal feedback&nbsp;





------------------ Original ------------------

**Comment by insecttt** [comment]
Hi, I'm using your module, it's great :)
But I don't use Digital signals, it didn't work.
But I use a string and analog signal, and it works great!

What do you mean to write
You need give the signal feedback & nbsp;
?

greetings

pon., 1 cze 2020 o 02:43 songzh96 <notifications@github.com> napisał(a):

**Comment by songzh96** [comment]
The Crestron Module Digital FeedBack，when it is 1, send false. it will be working.

**Comment by songzh96** [comment]
Hi， Have you tested it？Do you understand what I mean?

**Comment by jscales4000** [comment]
I have tested it but maybe I am not understanding what I should be doing. I set up two injects in node-red one with a string of "0" the other with a string of "1". the "1" trigger will activate the digital true in simpl windows but the zero does nothing. I could end up just using the analogs to make it work but wanted to get an idea for the digitals on what I may be doing wrong.

**Comment by songzh96** [comment]
Please use set/reset module
True link set, false link reset, the out link the status







------------------ Original ------------------

**Comment by insecttt** [comment]
Hi, thanks for the info. Now I have no way of checking and testing this. I will reply as soon as I check it. greetings

Wysłane z iPhone'a

**Comment by jscales4000** [comment]
Hi, my issue is that I am unable to get the false feedback joins to be triggered from node-red into crestron. At the moment I can only see true commands fed from node-red into the module, when a false command is sent to crestron, nothing happens on the false join. If both the true and false join will activate based on the feedback sent from node-red, then the set/reset join would be perfect to give you a single name that can change based on state but at the moment all i get is a momentary true

**Comment by songzh96** [comment]
try to use the new module
